feat: passing parameters to "run" is a warning

diff --git a/jh-github-dc b/jh-github-dc
--- a/jh-github-dc
+++ b/jh-github-dc
@@ -180,6 +180,12 @@ case "$CMD" in
     ;;
 
 "run")
+    if env | grep PARAM_ ; then
+        echo "You can not call 'run' with options" >&2
+        echo "::warning::You can not call 'run' with options (this will be an error in the future)"
+        # TODO: exit 1
+    fi
+
     docker_exec bash -c "$CMD_ARG" 2>&1
     ;;
 
